name: Create Branch Only

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the branch to create'
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create branch if it doesn't exist
        run: |
          git fetch origin
          if ! git ls-remote --exit-code --heads origin "${{ inputs.branch_name }}"; then
            git checkout -b "${{ inputs.branch_name }}"
            git commit --allow-empty -m "Initialize branch ${{ inputs.branch_name }}"
            git push origin "${{ inputs.branch_name }}"
          else
            echo "Branch '${{ inputs.branch_name }}' already exists on remote."
          fi
